### ISSUE TITLE
Feature: Make scopes configurable

### ISSUE THREAD

**Issue by simongottschlag** [manicminer/hamilton#12]
Hi @manicminer!

See this as and idea / feature request.

It would be a nice feature if scopes was configurable, to make it possible to use the auth package to get access tokens for plain AAD applications.

I'm using azidentity right now for this. Would be able to slim down my dependencies to only your lib.

**Comment by manicminer** [comment]
Hi @simongottschlag, thanks for requesting!

I've just merged a refactor of the auth package which exports the underlying authorizers for the client credentials flow.

Whilst the helper functions `auth.NewClientSecretAuthorizer()` and `auth.NewClientCertificateAuthorizer()` necessarily accept an `auth.Api` to determine the scopes to request, you should now be able implement these yourself if you want to request scopes for your own application.

I believe something like this should work:

```go
var (
	myAppIdUri   = "https://app.myorg.net"
	clientId     = "00000000-0000-0000-0000-000000000000"
	clientSecret = "qwertyuiop"
	tenantId     = "00000000-0000-0000-0000-000000000000"
)

conf := ClientCredentialsConfig{
	ClientID:     clientId,
	ClientSecret: clientSecret,
	Scopes:       fmt.Sprintf("%s/%s", myAppIdUri, ".default"),
	TokenURL:     auth.TokenEndpoint(environments.Global.AzureADEndpoint, tenantId, auth.TokenVersion2),
}

authorizer := conf.TokenSource(ctx, ClientCredentialsSecretType)
```

Let me know if you can get this to work :)

**Comment by simongottschlag** [comment]
Hi @manicminer! Would this work with Azure CLI and MSI auth as well?

Right now, I'm providing all three as options :)

**Comment by manicminer** [comment]
@simongottschlag Sorry for the delay in replying, I missed your question! You likely worked this out already, but yes it will sort of work for MSI auth (which issues a v1 token, so you should provide a resource URL rather than a scope).

The Azure CLI, wraps the token functionality in the commandline argument `--resource-type` that only supports a limited set of values (see `az account get-access-token --help`), of which Hamilton only exposes the `ms-graph` and `aad-graph` options at this time.

**Comment by manicminer** [comment]
I believe this functionality exists now, would you be happy to close this issue or did I perhaps miss something? Thanks!
