### ISSUE TITLE
Is it possible to make msgraph.Group a hashable type?

### ISSUE THREAD

**Issue by maxsokolovsky** [manicminer/hamilton#159]
I see many fields on the Group struct are pointers to slices. Is this to ensure the value can be used as a key in a map?

The Group value is something that would be fit for caching. There are a few fields whose types do not allow values of type Group to be hashable for some implementations of an LRU cache. For example, `[]GroupType` and `[]GroupResourceBehaviorOption`.

Since many slice fields are already pointers to a slice, is it possible to convert those remaining fields' types to pointer to a slice, so that Group may be used as a key in a map?

Also, the GroupsClient returns not a slice of group pointers `[]*Group`, but a pointer to a slice of groups `*[]Group`? Is this intentional as well?

**Comment by manicminer** [comment]
Hi @maxsokolovsky, thanks for the questions.

The use of pointers in the model structs is generally to play nice with Go's json marshaler. Behavioral differences between json `null`, zero values and omitting a field vary wildy between APIs and even between fields on the same object.

Some fields that are not pointer references are likely holdovers and can probably be updated. You're welcome to open a PR for these 👍 

Clients that return pointers are intentional, since these could be nil in the event of an API error. However, if a client method returns a nil error, then the result can be reasonably expected to be non-nil.

**Comment by maxsokolovsky** [comment]
@manicminer, thanks for your response! I will open a PR with those holdovers fields updated to be pointer types!

About the last part - since clients return collections of things (slices), the first returned value doesn't have to be a pointer type, and can be nil in case of an error, since the default empty value for a slice of anything is nil. Would it also be more memory-efficient to copy a `[]*Group` rather than `*[]Group` across functions?
