### ISSUE TITLE
Can "encoding/json" be replaced?

### ISSUE THREAD

**Issue by vijayrajah** [manicminer/hamilton#258]
I'm trying to get a list of all SPs in my org (from $WORK)

this is the code 
```
spClient := msgraph.NewServicePrincipalsClient()
	spClient.BaseClient.Authorizer = sdkAuth

	opts := odata.Query{
		Select: []string{"displayName", "appId", "id", "keyCredentials", "passwordCredentials"},
	}

	sps, _, err := spClient.List(ctx, opts)
	if err != nil {
		log.Error().Err(err).Msg("unable to get list of SPs")
		return err
	}
```

This is taking too long. (my org has > 3k) SPs.

When I profiled the code, I see that most of the CPU cycles are spent on JSON Unmarshillng & Marshilling

![image](https://github.com/manicminer/hamilton/assets/4451012/3e44306a-b7af-4756-b293-d4f55b388670)

is there a way to use other JSON libraries to speed-up the performance?

**Comment by manicminer** [comment]
Hi @vijayrajah, at this time I don't think we'll move away from the stdlib json library. If you haven't already, you might want to look at trimming down the response by using a [$select](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#select-parameter) query to remove any fields you don't need.

There is an active golang proposal for an [encoding/json/v2](https://github.com/golang/go/discussions/63397) package; if it hasn't been mentioned already there, it may be worth commenting on any performance issues with the current library so that the maintainers can be more aware going forward.
