### ISSUE TITLE
Support providing an HttpClient

### ISSUE THREAD

**Issue by adamconnelly** [manicminer/hamilton#82]
At the moment the HttpClient used isn't exported, which means it's not possible to use a custom client. Just to give some background, the reason I want to be able to do this is to provide a custom client that adds tracing of HTTP requests.

I've created a fork to quickly test out replacing the client by making it exported: https://github.com/adamconnelly/hamilton/commit/11eb20ad43b38e4f076fc212c2d0222f5117332e. That allows me to create a client like this:

```go
client := msgraph.NewApplicationsClient(tenantID)
client.BaseClient.Authorizer = authorizer
client.BaseClient.HttpClient = tracedClient
```

That works great, but I wanted to check a couple of things:

- Would you accept a contribution to allow this?
- Is the approach I've taken ok, or would you rather the client wasn't exported and was passed as an option to the `NewApplicationsClient()` function, or something along those lines?

Thanks!

**Comment by manicminer** [comment]
Hi @adamconnelly, thanks for requesting this! I've been working on a PR #78 to provide more flexibility when using `msgraph.Client{}` and have included this in that change.

Whilst the http client is now exported, so you can replace it if you wish, we're also now making use of [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) to handle request retries instead of the big for-loop in the `performRequest()` method. If you opt to supply your own client you will lose this capability so you might wish to factor that into your own http.Client.

However, also included is the ability to inject middleware functions for manipulating or copying the request and response structs. We'll be making use of this in the Terraform AzureAD provider to implement logging, see https://github.com/hashicorp/terraform-provider-azuread/blob/f/logging/internal/common/client_options.go#L29-L80 for an example.

Would either of these approaches work for you?

**Comment by adamconnelly** [comment]
@manicminer that all sounds great. The approach of swapping out the client would probably be better for us for now, just because it means we can use a consistent client for all our HTTP requests, but I think both approaches could work for us.

Do you have a rough idea of when you're expecting to merge your PR? Not trying to rush you - just so I can figure out to just wait or if I need to temporarily fork until that's ready.

Thanks for the quick response!

**Comment by manicminer** [comment]
@adamconnelly Will probably merge and release today - releases have generally been on Tuesdays but this week is a little late

**Comment by manicminer** [comment]
Resolved with #78

**Comment by adamconnelly** [comment]
@manicminer just wanted to say thanks - that worked perfectly. It's actually a bit better for our use-case now because we can use go-retryablehttp without having retries on 404s by default.

**Comment by manicminer** [comment]
@adamconnelly Great, that's good to hear :)

Note you can also set the `DisableRetries` field to true to stop the consistency related retries, eg on 404
