### ISSUE TITLE
EntitlementManagement - AccessPackages

### ISSUE THREAD

**Issue by kaovd** [manicminer/hamilton#92]
General Issue tracker for everything related to AccessPackage implementation within Identity & Governance Management. Will leave PR in draft state any comments, suggestions or contributions welcome 

https://docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta

- [x] accessPackage
- [x] accessPackageAssignmentPolicy
- [x] accessPackageCatalog
- [x] accessPackageResourceRequest - Non-Standard Implementation (For adding resources to Catalogs)
- [x]  accessPackageResource - RO Non-Standard

Rest of endpoints do not have Creation/Deletion capabiltity / Directly related to IDAG IaC flows

**Comment by kaovd** [comment]
@manicminer Could you potentially give some of this a  glance on in the draft PR? The first three endpoints are pretty straightforward CRUD, but "accessPackageResourceRequest" endpoint only has List and Create availiable where having some workaround implementation on the SDK would be needed. Specifically take a look at accesspackageresourcerequest.go - In order to delete you need to POST as if it where a Create Method. Also seems to be some lag on the backend potentially if youve just created an AP / Group to waited the Create func for 15s

Return is also a bit weird as a resource creation request != resource, therefore the resource ID (but the ID of the Request) is not returned and while can be figured out via pseduo get method on the corresponding tests file (L92) its a bit weird

Let me know what you think about it,  if we are ok with a few work arounds and impact on downstream implemnetation this is definetly do-able, elsewise will remove accessPackageResourceRequest  for this PR

Tests so far are all good
ok      github.com/manicminer/hamilton/msgraph  27.013s

**Comment by kaovd** [comment]
@petr-stupka Thanks this is extremely useful, understood requests are non standard and have a pseduo delete using admin remove. Have pretty much done exactly what youve said if you look at the PR

 Mustve looked over the execute immediately option - Will add, @manicminer will leave Consistency func in but should shorten time if we are OK to hardcore that? No idea why wouldnt be always on.

Elsewise have an issue with the RoleScope endpoint, from what i currently understand once a request has been done to add something to a Catalog, you call the RoleScope endpoint to add it to an AP - but Theres no deletion capability so i cant implement it? Unless its just not documented properly - would be big help if you know.

**Comment by petr-stupka** [comment]
@kaovd pls don't take me wrong if i say something what is already in, i need to dig in your PR to have full understanding. We have PowerShell script for that and i spend some time to understand the dependencies and the process so i'm happy to try to explain questions you may have to be able to complete it or help with some development. So will give you info about the RoleScopes asap

**Comment by kaovd** [comment]
Thanks, interested to see potential implementations

**Comment by petr-stupka** [comment]
## Documentation

For the development I used two documentation as both of them missing some important information and reference

MS Graph: https://docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta

Powershell: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/?view=graph-powershell-beta

Powershell cmdlets have `BodyParameter` input, which is basically Graph API request body body and all the properties are listed (in a bit messy way)

As example `AccessPackageResourceRequest` and the `executeImmediately` parameter. You can find it in [PWSH](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/new-mgentitlementmanagementaccesspackageresourcerequest?view=graph-powershell-beta) under BODYPARAMETER object (json object) docs and it is not in the Graph Documentation examples.

## RoleScope

_from what I currently understand once a request has been done to add something to a Catalog, you call the RoleScope endpoint to add it to an AccessPackage in the catalog_

that's correct.

To delete it, pwsh have cmdlet for it. And I assume the cmdlet just set `null` because of as you said, there is no endpoint for that

This can be done on `AccessPackage` object

see: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/update-mgentitlementmanagementaccesspackage?view=graph-powershell-beta

BODYPARAMETER object / [AccessPackageResourceRoleScopes <IMicrosoftGraphAccessPackageResourceRoleScope[]>]: Nullable

as this sis array, the specific object in the array is deleted (replaced by null?)

**Comment by kaovd** [comment]
After a bit of battling and looking at requests in Azure Portal itself, I've finally figured out where in the world some of these endpoints actually are.

The RoleScope DELETE endpoint is not documented, however as you mentioned @petr-stupka it is in Ms Graph Powershell Beta, only problem is its not implemented properly there as it does not work 

![image](https://user-images.githubusercontent.com/29356754/132988381-0c31b568-44ea-48bd-97f5-5ea88c995eac.png)

Not sure if what you found was any different - This is effectively doing DELETE accessPackages/id/accessPackageRoleScopes/id

However, looking at portal behaviour as obviously this endpoint has to exist somewhere - we see

DELETE accessPackages/id/accessPackageRoleScopes
with a Body of the resource, which is standard Creation style behaviour. However its used in a delete context here and comes back with 200
![image](https://user-images.githubusercontent.com/29356754/132989461-7543a938-154c-42aa-ae4f-580fdf14e0bd.png)


For the rest of the UPDATE Methods in pwsh but not the docs I'm going to assume it just deletes and recreates the resources or dosen't work - I want to deviate from the docs as least as possible for SDK Sanity

Only problem is this DELETE endpoint is broken in offical MS Graph Endpoint - Also it requires a body which is weird for DELETE behaviour
![image](https://user-images.githubusercontent.com/29356754/132996172-0cadd04b-de05-4bb5-9fa9-101585191819.png)

I have no idea what its complaining does not fall in range using same requests as Azure Portal - so I'm not going to try and keep attempting to implement an undocumented endpoint - although even if I could not sure if its SDK legal

Meantime I will implement the Create, List and pseduo Get endpoints but will be unusable downstream (terraform) as theres no delete

**Comment by petr-stupka** [comment]
Yeah, the PowerShell module is full of bugs (first release). Many cmdlet's often reference v1 instead of beta or have other bugs in it.

I think you right with the endpoint .. let's check thatin Microsoft Graph metadata instead of searching MS Docs: https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/beta/openapi.yaml

search for this operation:
`identityGovernance.entitlementManagement.accessPackageCatalogs.accessPackages.DeleteAccessPackageResourceRoleScopes`

![image](https://user-images.githubusercontent.com/18548253/133000811-6ae1eec8-0ec2-4ada-9e2d-402da527c69b.png)

you can see example how to form the request:
`/identityGovernance/entitlementManagement/accessPackageCatalogs/{accessPackageCatalog-id}/accessPackages/{accessPackage-id}/accessPackageResourceRoleScopes/{accessPackageResourceRoleScope-id}/accessPackageResourceRole`

as I can see there is no `requestBody` required like on 'patch' operation

btw, https://github.com/microsoftgraph/msgraph-metadata as source for informations

**Comment by petr-stupka** [comment]
Hi @kaovd had you chance to test it. I'm interested if the Graph Metadata can be used as reliable source. Btw, if I can help with any part of the development, please let me know

**Comment by kaovd** [comment]
> Hi @kaovd had you chance to test it? I'm interested if the Graph Metadata can be used as reliable source. Btw, if I can help with any part of the development, please let me know

@petr-stupka some reason git didnt notify me on the thread just seen this, will test again today

**Comment by kaovd** [comment]
@petr-stupka It dosen't seem the endpoints actually exist - as mentioned the closest thing I got was what the portal throws back which is at  DELETE /identityGovernance/entitlementManagement/accessPackages/{id}/accessPackageResourceRoleScopes but takes a request body in the delete for some reason - even structing it perfectly though this does not work and throws and argument error.

Your welcome to experiment in graph explorer https://developer.microsoft.com/en-us/graph/graph-explorer and try to figure out if any improperly documented endpoint for it exists and go create a sample package in the portal and assign a group at a root scope - but elsewise dont see any way around this one than creating the scopes via null resource pwsh provsioner or something like that with tf output downstream, will wait for your response but if no dice then will just go ahead with current implemenation

**Comment by petr-stupka** [comment]
Hi @kaovd I'm not sure how they doing it in the portal as seems like they have some logic behind. The endpoint returned from portal referenced v1 which is completely wrong - entitlementManagement is not available in v1 only in beta. So this is weird.

I tried digging into graph-explored - no success with delete operation.
Looking in our PowerShell script, we do not have the method to delete 'AccessPackagesResourceRoleScopes' we just recreate the AccessPackage

Then (until the method will be available) it can be also created is following way:

1. Create Catalog
2. Create Catalog Resources
3. Create AccessPackage with argument `AccessPackagesResourceRoleScopes' containing array of  `AccessPackagesResourceRoleScope` objects

So if someone would need to remove object from the 'AccessPackagesResourceRoleScopes' array the whole 'AccessPackage' would 'force new".
I know it is a bit limiting because of deleting 'AccessPackage' will also delete all the assignments however it can be some kind of workaround until the endpoint will be available.

Or as you said, let the 'AccessPackagesResourceRoleScopes' to be managed using portal, null_resource, or any other way until the endpoint is there - where i agree it may be the right way for now, not to complicate it at the moment and at least get the available resources into azurerm provider

Another option how to progress on it is to open issue in the graph-repo asking the guys how to perform the operation (will do it) or if the Hashicorp guys (@manicminer) have MSFT support contact (and I believe they have) to request the endpoint/information

**Comment by kaovd** [comment]
@petr-stupka Yep opening the issue would be great thanks.

If we can force new the AP that actually works out pretty well and can be a downstream implementation. Imagine the AP Resource will have a role scopes block then separate resources for catalogs, policy and resource requests.

**Comment by manicminer** [comment]
Just weighing in, both the portal and Azure CLI (not sure about the various pwsh modules) aren't always a great model of behavior as they hold special first-party access tokens that allow them to query undocumented endpoints. Often those endpoints are "private" or otherwise behave differently depending on whether a first-party access token or a regular token are used for authorization. This was common in the AAD Graph API and it's entirely possible the same sort of thing has been done in places with MS Graph.

**Comment by kaovd** [comment]
@manicminer was pretty much the logic I went along but just seems the graph backend isnt there yet. Not a problem though likely to have the full IDAG flow by working around downstream with as mentioned force replacmenets where needed.

**Comment by petr-stupka** [comment]
@kaovd in the meantime I've raised the question within our internal team (MVPs) if they can reach any of the MSFT product group working with MS Graph. Once I will get any feedback I will let you know.

**Comment by petr-stupka** [comment]
@kaovd just quick update from MSFT. The current beta API is the latest implementation of API which has been ready to ship. The missing API endpoint for delete operation will be released in the future (without ETA)

**Comment by kaovd** [comment]
> @kaovd just quick update from MSFT. The current beta API is the latest implementation of API which has been ready to ship. The missing API endpoint for delete operation will be released in the future (without ETA)

Well suppose thats reassuring that we can just toggle 1.0 or whatever they push to when they are done. For now the way i planned it downstream should work although still few things to raise with them
